#!/usr/bin/env node

/* 
 * Expand valid JSON-LD file. 
 * 
 * Dependency: 
 *   $ node install jsonld
 */
var jsonld = require('jsonld');

const args = process.argv.slice(2);
if (args.length != 1) {
  console.error("Expecting 1 argument: <json path>");  
  process.exit(1);
}

const json = require(`${process.cwd()}/${args[0]}`);

jsonld.expand(json, (err,out) => {
    if (err) {
        console.error(`Error: ${err}`);
        process.exit(2);
    } else {
        console.log(JSON.stringify(out, null, 2));
    }
});

