#!/usr/bin/env ruby
#
# Generate a random DNA sequence of specified length
#

def error(msg, code)
  STDERR.puts msg
  exit code
end

error "Requires one argument, found: #{ARGV.length}", 1 unless ARGV.length == 1

dec = ARGV[0]
error "Not a positive decimal number: #{dec}", 1 unless dec =~ /^\d+$/

dec.to_i.times do |i|
  putc "AGTC".chars.to_a.sample
end
puts

