#!/usr/bin/env ruby
#
# Generate a random DNA sequence of specified length
#

def error(msg, code)
  STDERR.puts msg
  exit code
end

error "Requires one argument, found: #{ARGV.length}", 1 unless ARGV.length == 1

error "Not a positive decimal number: #{dec}", 1 unless ARGV[0] =~ /^\d+$/

ARGV[0].to_i.times { putc "AGTC".chars.to_a.sample }
puts

